In [1]:
import pandas as pd

In [4]:
data = pd.read_csv("D:\GAME SETUPS\data.csv")

In [5]:
data

Date/Time  Temp_C  Dew Point Temp_C  Rel Hum_%  Wind Speed_km/h  \
0        1/1/2012 0:00    -1.8              -3.9         86                4   
1        1/1/2012 1:00    -1.8              -3.7         87                4   
2        1/1/2012 2:00    -1.8              -3.4         89                7   
3        1/1/2012 3:00    -1.5              -3.2         88                6   
4        1/1/2012 4:00    -1.5              -3.3         88                7   
...                ...     ...               ...        ...              ...   
8779  12/31/2012 19:00     0.1              -2.7         81               30   
8780  12/31/2012 20:00     0.2              -2.4         83               24   
8781  12/31/2012 21:00    -0.5              -1.5         93               28   
8782  12/31/2012 22:00    -0.2              -1.8         89               28   
8783  12/31/2012 23:00     0.0              -2.1         86               30   

      Visibility_km  Press_kPa               Weather  
0               8.0     101.24                   Fog  
1               8.0     101.24                   Fog  
2               4.0     101.26  Freezing Drizzle,Fog  
3               4.0     101.27  Freezing Drizzle,Fog  
4               4.8     101.23                   Fog  
...             ...        ...                   ...  
8779            9.7     100.13                  Snow  
8780            9.7     100.03                  Snow  
8781            4.8      99.95                  Snow  
8782            9.7      99.91                  Snow  
8783           11.3      99.89                  Snow  

[8784 rows x 8 columns]

In [10]:
data.head(10)

Date/Time  Temp_C  Dew Point Temp_C  Rel Hum_%  Wind Speed_km/h  \
0  1/1/2012 0:00    -1.8              -3.9         86                4   
1  1/1/2012 1:00    -1.8              -3.7         87                4   
2  1/1/2012 2:00    -1.8              -3.4         89                7   
3  1/1/2012 3:00    -1.5              -3.2         88                6   
4  1/1/2012 4:00    -1.5              -3.3         88                7   
5  1/1/2012 5:00    -1.4              -3.3         87                9   
6  1/1/2012 6:00    -1.5              -3.1         89                7   
7  1/1/2012 7:00    -1.4              -3.6         85                7   
8  1/1/2012 8:00    -1.4              -3.6         85                9   
9  1/1/2012 9:00    -1.3              -3.1         88               15   

   Visibility_km  Press_kPa               Weather  
0            8.0     101.24                   Fog  
1            8.0     101.24                   Fog  
2            4.0     101.26  Freezing Drizzle,Fog  
3            4.0     101.27  Freezing Drizzle,Fog  
4            4.8     101.23                   Fog  
5            6.4     101.27                   Fog  
6            6.4     101.29                   Fog  
7            8.0     101.26                   Fog  
8            8.0     101.23                   Fog  
9            4.0     101.20                   Fog

In [9]:
data.shape

(8784, 8)

In [11]:
data.index

RangeIndex(start=0, stop=8784, step=1)

In [12]:
data.columns

Index(['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%',
       'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='object')

In [13]:
l = list(data.columns)

In [14]:
l

['Date/Time',
 'Temp_C',
 'Dew Point Temp_C',
 'Rel Hum_%',
 'Wind Speed_km/h',
 'Visibility_km',
 'Press_kPa',
 'Weather']

In [18]:
l.max()

AttributeError: 'list' object has no attribute 'max'

In [19]:
for i in l:
    print(i)

Date/Time
Temp_C
Dew Point Temp_C
Rel Hum_%
Wind Speed_km/h
Visibility_km
Press_kPa
Weather


In [20]:
data.dtypes

Date/Time            object
Temp_C              float64
Dew Point Temp_C    float64
Rel Hum_%             int64
Wind Speed_km/h       int64
Visibility_km       float64
Press_kPa           float64
Weather              object
dtype: object

In [21]:
data.unique

AttributeError: 'DataFrame' object has no attribute 'unique'

In [22]:
data.unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [23]:
l

['Date/Time',
 'Temp_C',
 'Dew Point Temp_C',
 'Rel Hum_%',
 'Wind Speed_km/h',
 'Visibility_km',
 'Press_kPa',
 'Weather']

In [26]:
a = data['Temp_C'].unique()

In [27]:
a

array([ -1.8,  -1.5,  -1.4,  -1.3,  -1. ,  -0.5,  -0.2,   0.2,   0.8,
         1.8,   2.6,   3. ,   3.8,   3.1,   3.2,   4. ,   4.4,   5.3,
         5.2,   4.6,   3.9,   3.7,   2.9,   2.3,   2. ,   1.9,   1.5,
         2.2,   1.7,   1.1,   0. ,  -0.7,  -2.1,  -4.1,  -4.8,  -5.6,
        -5.8,  -7. ,  -7.4,  -9. ,  -9.7, -10.5, -11.3, -12.6, -12.9,
       -13.3, -14. , -14.8, -15. , -15.3, -14.9, -15.1, -15.8, -16.3,
       -16.9, -17.3, -17. , -17.1, -17.5, -17.9, -18.1, -18.5, -18.6,
       -18.2, -17.8, -16.8, -15.2, -14.2, -13.7, -12.4, -10.2,  -9.4,
        -8.9,  -8.4,  -7.8,  -7.6,  -9.5,  -9.6,  -8.8,  -7.5,  -5.4,
        -5. ,  -8.2,  -7.1,  -6.1,  -6.6,  -6. ,  -4.7,  -4.4,  -5.1,
        -4.3,  -6.7,  -9.2,  -9.8,  -9.9, -10. , -10.6, -11.8, -12. ,
       -14.4, -12.3, -12.5, -11.7, -11.9, -11.2, -11.5, -11.6,  -9.3,
        -8.7,  -8.5,  -8.1,  -6.9,  -6.4,  -5.7,  -5.5,  -3.7,  -3.6,
        -3.1,  -3.2,  -3. ,   0.4,   0.6,  -0.6,  -1.7,  -3.5,  -5.9,
        -6.5,  -7.2,

In [28]:
a.argmax()

509

In [29]:
a.max()

33.0

In [30]:
a.indexof('509')

AttributeError: 'numpy.ndarray' object has no attribute 'indexof'

In [31]:
a.index(509)

AttributeError: 'numpy.ndarray' object has no attribute 'index'

In [32]:
a.index(33)

AttributeError: 'numpy.ndarray' object has no attribute 'index'

In [33]:
a.index(33.0)

AttributeError: 'numpy.ndarray' object has no attribute 'index'

In [34]:
a.where(index=509)

AttributeError: 'numpy.ndarray' object has no attribute 'where'

In [35]:
a

array([ -1.8,  -1.5,  -1.4,  -1.3,  -1. ,  -0.5,  -0.2,   0.2,   0.8,
         1.8,   2.6,   3. ,   3.8,   3.1,   3.2,   4. ,   4.4,   5.3,
         5.2,   4.6,   3.9,   3.7,   2.9,   2.3,   2. ,   1.9,   1.5,
         2.2,   1.7,   1.1,   0. ,  -0.7,  -2.1,  -4.1,  -4.8,  -5.6,
        -5.8,  -7. ,  -7.4,  -9. ,  -9.7, -10.5, -11.3, -12.6, -12.9,
       -13.3, -14. , -14.8, -15. , -15.3, -14.9, -15.1, -15.8, -16.3,
       -16.9, -17.3, -17. , -17.1, -17.5, -17.9, -18.1, -18.5, -18.6,
       -18.2, -17.8, -16.8, -15.2, -14.2, -13.7, -12.4, -10.2,  -9.4,
        -8.9,  -8.4,  -7.8,  -7.6,  -9.5,  -9.6,  -8.8,  -7.5,  -5.4,
        -5. ,  -8.2,  -7.1,  -6.1,  -6.6,  -6. ,  -4.7,  -4.4,  -5.1,
        -4.3,  -6.7,  -9.2,  -9.8,  -9.9, -10. , -10.6, -11.8, -12. ,
       -14.4, -12.3, -12.5, -11.7, -11.9, -11.2, -11.5, -11.6,  -9.3,
        -8.7,  -8.5,  -8.1,  -6.9,  -6.4,  -5.7,  -5.5,  -3.7,  -3.6,
        -3.1,  -3.2,  -3. ,   0.4,   0.6,  -0.6,  -1.7,  -3.5,  -5.9,
        -6.5,  -7.2,

In [36]:
a.max()

33.0

In [37]:
a.min()

-23.3

In [38]:
a.argmax()

509

In [39]:
a.argmin()

175

In [40]:
a.sort(axis=0)

In [41]:
a

array([-23.3, -23.2, -22.8, -22.2, -21.4, -21.3, -21.2, -21.1, -21. ,
       -20.7, -20.6, -20.3, -20. , -19.9, -19.6, -19.5, -19.3, -19.2,
       -19.1, -19. , -18.7, -18.6, -18.5, -18.4, -18.3, -18.2, -18.1,
       -18. , -17.9, -17.8, -17.7, -17.6, -17.5, -17.4, -17.3, -17.2,
       -17.1, -17. , -16.9, -16.8, -16.7, -16.6, -16.4, -16.3, -16.2,
       -16.1, -16. , -15.9, -15.8, -15.7, -15.5, -15.4, -15.3, -15.2,
       -15.1, -15. , -14.9, -14.8, -14.7, -14.6, -14.5, -14.4, -14.3,
       -14.2, -14. , -13.9, -13.8, -13.7, -13.6, -13.5, -13.4, -13.3,
       -13.2, -13.1, -13. , -12.9, -12.8, -12.7, -12.6, -12.5, -12.4,
       -12.3, -12.2, -12.1, -12. , -11.9, -11.8, -11.7, -11.6, -11.5,
       -11.4, -11.3, -11.2, -11.1, -11. , -10.9, -10.8, -10.7, -10.6,
       -10.5, -10.4, -10.3, -10.2, -10.1, -10. ,  -9.9,  -9.8,  -9.7,
        -9.6,  -9.5,  -9.4,  -9.3,  -9.2,  -9.1,  -9. ,  -8.9,  -8.8,
        -8.7,  -8.6,  -8.5,  -8.4,  -8.3,  -8.2,  -8.1,  -8. ,  -7.9,
        -7.8,  -7.7,

In [43]:
a.argmax()

532

In [44]:
a.argmin()

0

In [45]:
a.shape

(533,)

In [47]:
a.insert(32.1)

AttributeError: 'numpy.ndarray' object has no attribute 'insert'

In [48]:
a.pop()

AttributeError: 'numpy.ndarray' object has no attribute 'pop'

In [49]:
a.dtype

dtype('float64')

In [50]:
a

array([-23.3, -23.2, -22.8, -22.2, -21.4, -21.3, -21.2, -21.1, -21. ,
       -20.7, -20.6, -20.3, -20. , -19.9, -19.6, -19.5, -19.3, -19.2,
       -19.1, -19. , -18.7, -18.6, -18.5, -18.4, -18.3, -18.2, -18.1,
       -18. , -17.9, -17.8, -17.7, -17.6, -17.5, -17.4, -17.3, -17.2,
       -17.1, -17. , -16.9, -16.8, -16.7, -16.6, -16.4, -16.3, -16.2,
       -16.1, -16. , -15.9, -15.8, -15.7, -15.5, -15.4, -15.3, -15.2,
       -15.1, -15. , -14.9, -14.8, -14.7, -14.6, -14.5, -14.4, -14.3,
       -14.2, -14. , -13.9, -13.8, -13.7, -13.6, -13.5, -13.4, -13.3,
       -13.2, -13.1, -13. , -12.9, -12.8, -12.7, -12.6, -12.5, -12.4,
       -12.3, -12.2, -12.1, -12. , -11.9, -11.8, -11.7, -11.6, -11.5,
       -11.4, -11.3, -11.2, -11.1, -11. , -10.9, -10.8, -10.7, -10.6,
       -10.5, -10.4, -10.3, -10.2, -10.1, -10. ,  -9.9,  -9.8,  -9.7,
        -9.6,  -9.5,  -9.4,  -9.3,  -9.2,  -9.1,  -9. ,  -8.9,  -8.8,
        -8.7,  -8.6,  -8.5,  -8.4,  -8.3,  -8.2,  -8.1,  -8. ,  -7.9,
        -7.8,  -7.7,

In [51]:
import numpy as np

In [53]:
array = np.array(a)

In [54]:
a

array([-23.3, -23.2, -22.8, -22.2, -21.4, -21.3, -21.2, -21.1, -21. ,
       -20.7, -20.6, -20.3, -20. , -19.9, -19.6, -19.5, -19.3, -19.2,
       -19.1, -19. , -18.7, -18.6, -18.5, -18.4, -18.3, -18.2, -18.1,
       -18. , -17.9, -17.8, -17.7, -17.6, -17.5, -17.4, -17.3, -17.2,
       -17.1, -17. , -16.9, -16.8, -16.7, -16.6, -16.4, -16.3, -16.2,
       -16.1, -16. , -15.9, -15.8, -15.7, -15.5, -15.4, -15.3, -15.2,
       -15.1, -15. , -14.9, -14.8, -14.7, -14.6, -14.5, -14.4, -14.3,
       -14.2, -14. , -13.9, -13.8, -13.7, -13.6, -13.5, -13.4, -13.3,
       -13.2, -13.1, -13. , -12.9, -12.8, -12.7, -12.6, -12.5, -12.4,
       -12.3, -12.2, -12.1, -12. , -11.9, -11.8, -11.7, -11.6, -11.5,
       -11.4, -11.3, -11.2, -11.1, -11. , -10.9, -10.8, -10.7, -10.6,
       -10.5, -10.4, -10.3, -10.2, -10.1, -10. ,  -9.9,  -9.8,  -9.7,
        -9.6,  -9.5,  -9.4,  -9.3,  -9.2,  -9.1,  -9. ,  -8.9,  -8.8,
        -8.7,  -8.6,  -8.5,  -8.4,  -8.3,  -8.2,  -8.1,  -8. ,  -7.9,
        -7.8,  -7.7,

In [55]:
a.dtype

dtype('float64')

In [58]:
a.ndim

1

In [59]:
a.shape

(533,)

In [60]:
a.reshape(1,533)

array([[-23.3, -23.2, -22.8, -22.2, -21.4, -21.3, -21.2, -21.1, -21. ,
        -20.7, -20.6, -20.3, -20. , -19.9, -19.6, -19.5, -19.3, -19.2,
        -19.1, -19. , -18.7, -18.6, -18.5, -18.4, -18.3, -18.2, -18.1,
        -18. , -17.9, -17.8, -17.7, -17.6, -17.5, -17.4, -17.3, -17.2,
        -17.1, -17. , -16.9, -16.8, -16.7, -16.6, -16.4, -16.3, -16.2,
        -16.1, -16. , -15.9, -15.8, -15.7, -15.5, -15.4, -15.3, -15.2,
        -15.1, -15. , -14.9, -14.8, -14.7, -14.6, -14.5, -14.4, -14.3,
        -14.2, -14. , -13.9, -13.8, -13.7, -13.6, -13.5, -13.4, -13.3,
        -13.2, -13.1, -13. , -12.9, -12.8, -12.7, -12.6, -12.5, -12.4,
        -12.3, -12.2, -12.1, -12. , -11.9, -11.8, -11.7, -11.6, -11.5,
        -11.4, -11.3, -11.2, -11.1, -11. , -10.9, -10.8, -10.7, -10.6,
        -10.5, -10.4, -10.3, -10.2, -10.1, -10. ,  -9.9,  -9.8,  -9.7,
         -9.6,  -9.5,  -9.4,  -9.3,  -9.2,  -9.1,  -9. ,  -8.9,  -8.8,
         -8.7,  -8.6,  -8.5,  -8.4,  -8.3,  -8.2,  -8.1,  -8. ,  -7.9,
      

In [61]:
for i in range(1,534):
    if 533%i == 0:
        print(i)

1
13
41
533


In [63]:

533/41

13.0

In [64]:
533/13

41.0

In [65]:
a.reshape(13,41)

array([[-23.3, -23.2, -22.8, -22.2, -21.4, -21.3, -21.2, -21.1, -21. ,
        -20.7, -20.6, -20.3, -20. , -19.9, -19.6, -19.5, -19.3, -19.2,
        -19.1, -19. , -18.7, -18.6, -18.5, -18.4, -18.3, -18.2, -18.1,
        -18. , -17.9, -17.8, -17.7, -17.6, -17.5, -17.4, -17.3, -17.2,
        -17.1, -17. , -16.9, -16.8, -16.7],
       [-16.6, -16.4, -16.3, -16.2, -16.1, -16. , -15.9, -15.8, -15.7,
        -15.5, -15.4, -15.3, -15.2, -15.1, -15. , -14.9, -14.8, -14.7,
        -14.6, -14.5, -14.4, -14.3, -14.2, -14. , -13.9, -13.8, -13.7,
        -13.6, -13.5, -13.4, -13.3, -13.2, -13.1, -13. , -12.9, -12.8,
        -12.7, -12.6, -12.5, -12.4, -12.3],
       [-12.2, -12.1, -12. , -11.9, -11.8, -11.7, -11.6, -11.5, -11.4,
        -11.3, -11.2, -11.1, -11. , -10.9, -10.8, -10.7, -10.6, -10.5,
        -10.4, -10.3, -10.2, -10.1, -10. ,  -9.9,  -9.8,  -9.7,  -9.6,
         -9.5,  -9.4,  -9.3,  -9.2,  -9.1,  -9. ,  -8.9,  -8.8,  -8.7,
         -8.6,  -8.5,  -8.4,  -8.3,  -8.2],
       [ -8.1,  

In [66]:
a.reshape(41,13)

array([[-23.3, -23.2, -22.8, -22.2, -21.4, -21.3, -21.2, -21.1, -21. ,
        -20.7, -20.6, -20.3, -20. ],
       [-19.9, -19.6, -19.5, -19.3, -19.2, -19.1, -19. , -18.7, -18.6,
        -18.5, -18.4, -18.3, -18.2],
       [-18.1, -18. , -17.9, -17.8, -17.7, -17.6, -17.5, -17.4, -17.3,
        -17.2, -17.1, -17. , -16.9],
       [-16.8, -16.7, -16.6, -16.4, -16.3, -16.2, -16.1, -16. , -15.9,
        -15.8, -15.7, -15.5, -15.4],
       [-15.3, -15.2, -15.1, -15. , -14.9, -14.8, -14.7, -14.6, -14.5,
        -14.4, -14.3, -14.2, -14. ],
       [-13.9, -13.8, -13.7, -13.6, -13.5, -13.4, -13.3, -13.2, -13.1,
        -13. , -12.9, -12.8, -12.7],
       [-12.6, -12.5, -12.4, -12.3, -12.2, -12.1, -12. , -11.9, -11.8,
        -11.7, -11.6, -11.5, -11.4],
       [-11.3, -11.2, -11.1, -11. , -10.9, -10.8, -10.7, -10.6, -10.5,
        -10.4, -10.3, -10.2, -10.1],
       [-10. ,  -9.9,  -9.8,  -9.7,  -9.6,  -9.5,  -9.4,  -9.3,  -9.2,
         -9.1,  -9. ,  -8.9,  -8.8],
       [ -8.7,  -8.6,  -8.5,

In [67]:
a.ravel()

array([-23.3, -23.2, -22.8, -22.2, -21.4, -21.3, -21.2, -21.1, -21. ,
       -20.7, -20.6, -20.3, -20. , -19.9, -19.6, -19.5, -19.3, -19.2,
       -19.1, -19. , -18.7, -18.6, -18.5, -18.4, -18.3, -18.2, -18.1,
       -18. , -17.9, -17.8, -17.7, -17.6, -17.5, -17.4, -17.3, -17.2,
       -17.1, -17. , -16.9, -16.8, -16.7, -16.6, -16.4, -16.3, -16.2,
       -16.1, -16. , -15.9, -15.8, -15.7, -15.5, -15.4, -15.3, -15.2,
       -15.1, -15. , -14.9, -14.8, -14.7, -14.6, -14.5, -14.4, -14.3,
       -14.2, -14. , -13.9, -13.8, -13.7, -13.6, -13.5, -13.4, -13.3,
       -13.2, -13.1, -13. , -12.9, -12.8, -12.7, -12.6, -12.5, -12.4,
       -12.3, -12.2, -12.1, -12. , -11.9, -11.8, -11.7, -11.6, -11.5,
       -11.4, -11.3, -11.2, -11.1, -11. , -10.9, -10.8, -10.7, -10.6,
       -10.5, -10.4, -10.3, -10.2, -10.1, -10. ,  -9.9,  -9.8,  -9.7,
        -9.6,  -9.5,  -9.4,  -9.3,  -9.2,  -9.1,  -9. ,  -8.9,  -8.8,
        -8.7,  -8.6,  -8.5,  -8.4,  -8.3,  -8.2,  -8.1,  -8. ,  -7.9,
        -7.8,  -7.7,

In [68]:
a.ndim

1

In [72]:
b = a.reshape(41,13)

In [70]:
a.ndim

1

In [71]:
a.shape

(533,)

In [73]:
b.shape

(41, 13)

In [74]:
b.ndim

2

In [75]:
b.shape

(41, 13)

In [76]:
b[10:21]

array([[-7.4, -7.3, -7.2, -7.1, -7. , -6.9, -6.8, -6.7, -6.6, -6.5, -6.4,
        -6.3, -6.2],
       [-6.1, -6. , -5.9, -5.8, -5.7, -5.6, -5.5, -5.4, -5.3, -5.2, -5.1,
        -5. , -4.9],
       [-4.8, -4.7, -4.6, -4.5, -4.4, -4.3, -4.2, -4.1, -4. , -3.9, -3.8,
        -3.7, -3.6],
       [-3.5, -3.4, -3.3, -3.2, -3.1, -3. , -2.9, -2.8, -2.7, -2.6, -2.5,
        -2.4, -2.3],
       [-2.2, -2.1, -2. , -1.9, -1.8, -1.7, -1.6, -1.5, -1.4, -1.3, -1.2,
        -1.1, -1. ],
       [-0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ,  0.1,
         0.2,  0.3],
       [ 0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,  1.2,  1.3,  1.4,
         1.5,  1.6],
       [ 1.7,  1.8,  1.9,  2. ,  2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,
         2.8,  2.9],
       [ 3. ,  3.1,  3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,
         4.1,  4.2],
       [ 4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,
         5.4,  5.5],
       [ 5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2, 

In [77]:
b[10]+b[11]

array([-13.5, -13.3, -13.1, -12.9, -12.7, -12.5, -12.3, -12.1, -11.9,
       -11.7, -11.5, -11.3, -11.1])

In [78]:
len(b)
    

41

In [84]:
c = np.array(b,dtype = 'int64')

In [85]:
c

array([[-23, -23, -22, -22, -21, -21, -21, -21, -21, -20, -20, -20, -20],
       [-19, -19, -19, -19, -19, -19, -19, -18, -18, -18, -18, -18, -18],
       [-18, -18, -17, -17, -17, -17, -17, -17, -17, -17, -17, -17, -16],
       [-16, -16, -16, -16, -16, -16, -16, -16, -15, -15, -15, -15, -15],
       [-15, -15, -15, -15, -14, -14, -14, -14, -14, -14, -14, -14, -14],
       [-13, -13, -13, -13, -13, -13, -13, -13, -13, -13, -12, -12, -12],
       [-12, -12, -12, -12, -12, -12, -12, -11, -11, -11, -11, -11, -11],
       [-11, -11, -11, -11, -10, -10, -10, -10, -10, -10, -10, -10, -10],
       [-10,  -9,  -9,  -9,  -9,  -9,  -9,  -9,  -9,  -9,  -9,  -8,  -8],
       [ -8,  -8,  -8,  -8,  -8,  -8,  -8,  -8,  -7,  -7,  -7,  -7,  -7],
       [ -7,  -7,  -7,  -7,  -7,  -6,  -6,  -6,  -6,  -6,  -6,  -6,  -6],
       [ -6,  -6,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -4],
       [ -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -3,  -3,  -3,  -3],
       [ -3,  -3,  -3,  -3,  -3,  -3, 

In [86]:
c.dtype

dtype('int64')

In [87]:
d= c.view()

In [88]:
d

array([[-23, -23, -22, -22, -21, -21, -21, -21, -21, -20, -20, -20, -20],
       [-19, -19, -19, -19, -19, -19, -19, -18, -18, -18, -18, -18, -18],
       [-18, -18, -17, -17, -17, -17, -17, -17, -17, -17, -17, -17, -16],
       [-16, -16, -16, -16, -16, -16, -16, -16, -15, -15, -15, -15, -15],
       [-15, -15, -15, -15, -14, -14, -14, -14, -14, -14, -14, -14, -14],
       [-13, -13, -13, -13, -13, -13, -13, -13, -13, -13, -12, -12, -12],
       [-12, -12, -12, -12, -12, -12, -12, -11, -11, -11, -11, -11, -11],
       [-11, -11, -11, -11, -10, -10, -10, -10, -10, -10, -10, -10, -10],
       [-10,  -9,  -9,  -9,  -9,  -9,  -9,  -9,  -9,  -9,  -9,  -8,  -8],
       [ -8,  -8,  -8,  -8,  -8,  -8,  -8,  -8,  -7,  -7,  -7,  -7,  -7],
       [ -7,  -7,  -7,  -7,  -7,  -6,  -6,  -6,  -6,  -6,  -6,  -6,  -6],
       [ -6,  -6,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -4],
       [ -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -3,  -3,  -3,  -3],
       [ -3,  -3,  -3,  -3,  -3,  -3, 

In [89]:
c.view()

array([[-23, -23, -22, -22, -21, -21, -21, -21, -21, -20, -20, -20, -20],
       [-19, -19, -19, -19, -19, -19, -19, -18, -18, -18, -18, -18, -18],
       [-18, -18, -17, -17, -17, -17, -17, -17, -17, -17, -17, -17, -16],
       [-16, -16, -16, -16, -16, -16, -16, -16, -15, -15, -15, -15, -15],
       [-15, -15, -15, -15, -14, -14, -14, -14, -14, -14, -14, -14, -14],
       [-13, -13, -13, -13, -13, -13, -13, -13, -13, -13, -12, -12, -12],
       [-12, -12, -12, -12, -12, -12, -12, -11, -11, -11, -11, -11, -11],
       [-11, -11, -11, -11, -10, -10, -10, -10, -10, -10, -10, -10, -10],
       [-10,  -9,  -9,  -9,  -9,  -9,  -9,  -9,  -9,  -9,  -9,  -8,  -8],
       [ -8,  -8,  -8,  -8,  -8,  -8,  -8,  -8,  -7,  -7,  -7,  -7,  -7],
       [ -7,  -7,  -7,  -7,  -7,  -6,  -6,  -6,  -6,  -6,  -6,  -6,  -6],
       [ -6,  -6,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -4],
       [ -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -3,  -3,  -3,  -3],
       [ -3,  -3,  -3,  -3,  -3,  -3, 

In [94]:
c[0,1]=21

In [95]:
c

array([[ 21,  21,  21,  21,  21,  21,  21,  21,  21,  21,  21,  21,  21],
       [-19, -19, -19, -19, -19, -19, -19, -18, -18, -18, -18, -18, -18],
       [-18, -18, -17, -17, -17, -17, -17, -17, -17, -17, -17, -17, -16],
       [-16, -16, -16, -16, -16, -16, -16, -16, -15, -15, -15, -15, -15],
       [-15, -15, -15, -15, -14, -14, -14, -14, -14, -14, -14, -14, -14],
       [-13, -13, -13, -13, -13, -13, -13, -13, -13, -13, -12, -12, -12],
       [-12, -12, -12, -12, -12, -12, -12, -11, -11, -11, -11, -11, -11],
       [-11, -11, -11, -11, -10, -10, -10, -10, -10, -10, -10, -10, -10],
       [-10,  -9,  -9,  -9,  -9,  -9,  -9,  -9,  -9,  -9,  -9,  -8,  -8],
       [ -8,  -8,  -8,  -8,  -8,  -8,  -8,  -8,  -7,  -7,  -7,  -7,  -7],
       [ -7,  -7,  -7,  -7,  -7,  -6,  -6,  -6,  -6,  -6,  -6,  -6,  -6],
       [ -6,  -6,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -4],
       [ -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -3,  -3,  -3,  -3],
       [ -3,  -3,  -3,  -3,  -3,  -3, 

In [96]:
c

array([[ 21,  21,  21,  21,  21,  21,  21,  21,  21,  21,  21,  21,  21],
       [-19, -19, -19, -19, -19, -19, -19, -18, -18, -18, -18, -18, -18],
       [-18, -18, -17, -17, -17, -17, -17, -17, -17, -17, -17, -17, -16],
       [-16, -16, -16, -16, -16, -16, -16, -16, -15, -15, -15, -15, -15],
       [-15, -15, -15, -15, -14, -14, -14, -14, -14, -14, -14, -14, -14],
       [-13, -13, -13, -13, -13, -13, -13, -13, -13, -13, -12, -12, -12],
       [-12, -12, -12, -12, -12, -12, -12, -11, -11, -11, -11, -11, -11],
       [-11, -11, -11, -11, -10, -10, -10, -10, -10, -10, -10, -10, -10],
       [-10,  -9,  -9,  -9,  -9,  -9,  -9,  -9,  -9,  -9,  -9,  -8,  -8],
       [ -8,  -8,  -8,  -8,  -8,  -8,  -8,  -8,  -7,  -7,  -7,  -7,  -7],
       [ -7,  -7,  -7,  -7,  -7,  -6,  -6,  -6,  -6,  -6,  -6,  -6,  -6],
       [ -6,  -6,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -5,  -4],
       [ -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -3,  -3,  -3,  -3],
       [ -3,  -3,  -3,  -3,  -3,  -3, 

In [97]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [98]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
arr.dtype

dtype('int32')

In [101]:
arr.shape

(9,)

In [102]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [113]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
arr1 = arr.view()

In [116]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
arr1[0] = 12

In [118]:
arr1

array([12,  2,  3,  4,  5,  6,  7,  8,  9])

In [119]:
arr

array([12,  2,  3,  4,  5,  6,  7,  8,  9])

In [120]:
arr1

array([12,  2,  3,  4,  5,  6,  7,  8,  9])

In [121]:
arr

array([12,  2,  3,  4,  5,  6,  7,  8,  9])

In [127]:
arr.reshape(3,3)


array([[12,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [130]:
for i in arr:
    print(i)

12
2
3
4
5
6
7
8
9


In [142]:
arr2 = np.array([[[1,2,3],[4,5,6],[7,8,9]]],ndmin = 6)

In [143]:
arr2.shape

(1, 1, 1, 1, 3, 3)

In [144]:
for i in arr2:
    print(i)

[[[[[1 2 3]
    [4 5 6]
    [7 8 9]]]]]


In [145]:
for i in arr2:
    for j in i:
        print(j)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]


In [146]:
arr2

array([[[[[[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]]]]])

In [148]:
for x,y in np.ndenumerate(arr2):
    print(x,y)

(0, 0, 0, 0, 0, 0) 1
(0, 0, 0, 0, 0, 1) 2
(0, 0, 0, 0, 0, 2) 3
(0, 0, 0, 0, 1, 0) 4
(0, 0, 0, 0, 1, 1) 5
(0, 0, 0, 0, 1, 2) 6
(0, 0, 0, 0, 2, 0) 7
(0, 0, 0, 0, 2, 1) 8
(0, 0, 0, 0, 2, 2) 9


In [153]:
arr3 = np.array_split(arr2,6)

In [154]:
 arr3

[array([[[[[[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]]]]]]),
 array([], shape=(0, 1, 1, 1, 3, 3), dtype=int32),
 array([], shape=(0, 1, 1, 1, 3, 3), dtype=int32),
 array([], shape=(0, 1, 1, 1, 3, 3), dtype=int32),
 array([], shape=(0, 1, 1, 1, 3, 3), dtype=int32),
 array([], shape=(0, 1, 1, 1, 3, 3), dtype=int32)]

In [155]:
arr4 = np.array([[54,6,33,35],[23,435,64,23]])

In [158]:
arr4

array([[  6,  33,  35,  54],
       [ 23,  23,  64, 435]])

In [161]:
arr4.sort(axis=0)

In [162]:
arr4

array([[  6,  23,  35,  54],
       [ 23,  33,  64, 435]])

In [191]:
arr5 = np.array(['a','A','b','B'])

In [192]:
arr5

array(['a', 'A', 'b', 'B'], dtype='<U1')

In [193]:
print(np.sort(arr5))

['A' 'B' 'a' 'b']


In [194]:
print(np.searchsorted(arr5,'a'))

2


In [195]:
arr5.argmax()

2

In [196]:
arr5.argmin()

1

In [201]:
arr4.argmax()

7

In [202]:
data

Date/Time  Temp_C  Dew Point Temp_C  Rel Hum_%  Wind Speed_km/h  \
0        1/1/2012 0:00    -1.8              -3.9         86                4   
1        1/1/2012 1:00    -1.8              -3.7         87                4   
2        1/1/2012 2:00    -1.8              -3.4         89                7   
3        1/1/2012 3:00    -1.5              -3.2         88                6   
4        1/1/2012 4:00    -1.5              -3.3         88                7   
...                ...     ...               ...        ...              ...   
8779  12/31/2012 19:00     0.1              -2.7         81               30   
8780  12/31/2012 20:00     0.2              -2.4         83               24   
8781  12/31/2012 21:00    -0.5              -1.5         93               28   
8782  12/31/2012 22:00    -0.2              -1.8         89               28   
8783  12/31/2012 23:00     0.0              -2.1         86               30   

      Visibility_km  Press_kPa               Weather  
0               8.0     101.24                   Fog  
1               8.0     101.24                   Fog  
2               4.0     101.26  Freezing Drizzle,Fog  
3               4.0     101.27  Freezing Drizzle,Fog  
4               4.8     101.23                   Fog  
...             ...        ...                   ...  
8779            9.7     100.13                  Snow  
8780            9.7     100.03                  Snow  
8781            4.8      99.95                  Snow  
8782            9.7      99.91                  Snow  
8783           11.3      99.89                  Snow  

[8784 rows x 8 columns]

In [204]:
data.head()

Date/Time  Temp_C  Dew Point Temp_C  Rel Hum_%  Wind Speed_km/h  \
0  1/1/2012 0:00    -1.8              -3.9         86                4   
1  1/1/2012 1:00    -1.8              -3.7         87                4   
2  1/1/2012 2:00    -1.8              -3.4         89                7   
3  1/1/2012 3:00    -1.5              -3.2         88                6   
4  1/1/2012 4:00    -1.5              -3.3         88                7   

   Visibility_km  Press_kPa               Weather  
0            8.0     101.24                   Fog  
1            8.0     101.24                   Fog  
2            4.0     101.26  Freezing Drizzle,Fog  
3            4.0     101.27  Freezing Drizzle,Fog  
4            4.8     101.23                   Fog

In [205]:
data.columns

Index(['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%',
       'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='object')

In [206]:
l = list(data.columns)

In [207]:
l

['Date/Time',
 'Temp_C',
 'Dew Point Temp_C',
 'Rel Hum_%',
 'Wind Speed_km/h',
 'Visibility_km',
 'Press_kPa',
 'Weather']

In [208]:
t = tuple(l)

In [209]:
t

('Date/Time',
 'Temp_C',
 'Dew Point Temp_C',
 'Rel Hum_%',
 'Wind Speed_km/h',
 'Visibility_km',
 'Press_kPa',
 'Weather')

In [210]:
s = set(t)

In [211]:
s

{'Date/Time',
 'Dew Point Temp_C',
 'Press_kPa',
 'Rel Hum_%',
 'Temp_C',
 'Visibility_km',
 'Weather',
 'Wind Speed_km/h'}

In [213]:
s.add('hello')

In [215]:
s.remove('hello')

In [216]:
s

{'Date/Time',
 'Dew Point Temp_C',
 'Press_kPa',
 'Rel Hum_%',
 'Temp_C',
 'Visibility_km',
 'Weather',
 'Wind Speed_km/h'}

In [217]:
data

Date/Time  Temp_C  Dew Point Temp_C  Rel Hum_%  Wind Speed_km/h  \
0        1/1/2012 0:00    -1.8              -3.9         86                4   
1        1/1/2012 1:00    -1.8              -3.7         87                4   
2        1/1/2012 2:00    -1.8              -3.4         89                7   
3        1/1/2012 3:00    -1.5              -3.2         88                6   
4        1/1/2012 4:00    -1.5              -3.3         88                7   
...                ...     ...               ...        ...              ...   
8779  12/31/2012 19:00     0.1              -2.7         81               30   
8780  12/31/2012 20:00     0.2              -2.4         83               24   
8781  12/31/2012 21:00    -0.5              -1.5         93               28   
8782  12/31/2012 22:00    -0.2              -1.8         89               28   
8783  12/31/2012 23:00     0.0              -2.1         86               30   

      Visibility_km  Press_kPa               Weather  
0               8.0     101.24                   Fog  
1               8.0     101.24                   Fog  
2               4.0     101.26  Freezing Drizzle,Fog  
3               4.0     101.27  Freezing Drizzle,Fog  
4               4.8     101.23                   Fog  
...             ...        ...                   ...  
8779            9.7     100.13                  Snow  
8780            9.7     100.03                  Snow  
8781            4.8      99.95                  Snow  
8782            9.7      99.91                  Snow  
8783           11.3      99.89                  Snow  

[8784 rows x 8 columns]

In [218]:
data['Weather'].unique()

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 

In [219]:
data.nunique()

Date/Time           8784
Temp_C               533
Dew Point Temp_C     489
Rel Hum_%             83
Wind Speed_km/h       34
Visibility_km         24
Press_kPa            518
Weather               50
dtype: int64

In [220]:
data.count()

Date/Time           8784
Temp_C              8784
Dew Point Temp_C    8784
Rel Hum_%           8784
Wind Speed_km/h     8784
Visibility_km       8784
Press_kPa           8784
Weather             8784
dtype: int64

In [221]:
data['Weather'].value_counts()

Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                        

In [222]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Date/Time         8784 non-null   object 
 1   Temp_C            8784 non-null   float64
 2   Dew Point Temp_C  8784 non-null   float64
 3   Rel Hum_%         8784 non-null   int64  
 4   Wind Speed_km/h   8784 non-null   int64  
 5   Visibility_km     8784 non-null   float64
 6   Press_kPa         8784 non-null   float64
 7   Weather           8784 non-null   object 
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB
